### ISSUE TITLE
opdatering

### ISSUE THREAD

**Issue by stutoni** [ottopaulsen/MMM-Tibber#15]
Hei otto.
Etter oppdatering i går starter ikke speilet opp med Tibbermodulen installert.Det stod på speilet at det var en oppdatering til tibber og gjorde det med remote control modulen.Etter oppdatering og reset  startet ikke speilet opp det bare henger på electron svart skjerm.får å få speilet gang igjen må eg fjerne tibber modulen.Prøvde med en annen config uten hell. Prøvde også en fresh install av tibber modulen.

**Comment by ottopaulsen** [comment]
Hei, og takk bor beskjed. Beklager feilen, jeg tror jeg fikk med en endring som ikke skulle vært der. Den er ordnet nå. Kan du prøve å oppgradere og se om det løser problemet ditt?

Otto

**Comment by stutoni** [comment]
Hei Otto og takk for svar.Tok en ny install nå men det starter fortsatt ikke opp

**Comment by ottopaulsen** [comment]
Hmm. Kan du se hva slags feilmelding som skrives i loggen til MM?

**Comment by stutoni** [comment]
Her er noe:  
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'jsonpointer'
0|mm  | Require stack:
0|mm  | - /home/pi/MagicMirror/modules/MMM-Tibber/consumptions.js
0|mm  | - /home/pi/MagicMirror/modules/MMM-Tibber/node_helper.js
0|mm  | - /home/pi/MagicMirror/js/app.js
0|mm  | - /home/pi/MagicMirror/js/electron.js
0|mm  | - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|mm  |

**Comment by ottopaulsen** [comment]
Denne: 
`WARNING! Could not load config file. Starting with default configuration.`
tyder på at det er feil i config-fila di.

Denne:
`Cannot find module 'jsonpointer'`
kan tyde på at du ikke har kjørt `npm install` etter at du installerte modulen.

Forresten litt rart om du fikk begge samtidig.

Sjekk om du har en mappe som heter `jsonpointer` i enten `MagicMirror/node_modules` eller `MagicMirror/modules/MMM-Tibber/node_modules`. Hvis ikke, kjør `npm install` i `MMM-Tibber` mappa.

Videre må du få bort den config-feilen.

**Comment by stutoni** [comment]
Er veldig rart dette for før idag prøvde jeg på en annen raspberry og med samme feil.Har nå prøvd alle forslag men med samme feil og config er standard 

[27.09.2021 22:57.44.421] [ERROR] [31mWARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'jsonpointer'[39m
[31mRequire stack:[39m
[31m- /home/pi/MagicMirror/modules/MMM-Tibber/consumptions.js[39m
[31m- /home/pi/MagicMirror/modules/MMM-Tibber/node_helper.js[39m
[31m- /home/pi/MagicMirror/js/app.js[39m
[31m- /home/pi/MagicMirror/js/electron.js[39m
[31m- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js[39m
[31m- [39m
[27.09.2021 22:57.44.426] [ERROR] App threw an error during load
[27.09.2021 22:57.44.434] [ERROR] Error: Cannot find module 'jsonpointer'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Tibber/consumptions.js
- /home/pi/MagicMirror/modules/MMM-Tibber/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7718:16)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Tibber/consumptions.js:6:21)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Tibber/node_helper.js:5:22)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
[27.09.2021 22:57.44.437] [ERROR] Whoops! There was an uncaught exception...
[27.09.2021 22:57.44.447] [ERROR] Error: Cannot find module 'jsonpointer'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Tibber/consumptions.js
- /home/pi/MagicMirror/modules/MMM-Tibber/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-

**Comment by ottopaulsen** [comment]
Kan du bekrefte at `jsonpointer` ligger under `node_modules`? Hos meg ligger den under `MagicMirror/node_modules`. Prøv det, om den ikke ligger der (`npm install jsonpointer` fra `MagicMirror`).

Hvilken versjon av node har du (`node --version`)?

**Comment by stutoni** [comment]
Hei
Det var det som manglet. Jsonpointer kommer ikke med når jeg installerer og manglet i nodemappen.
Nodeversjon er 10.24 
configen er den samme 
Takk 


pi@raspberrypi:~/MagicMirror $ npm install jsonpointer
npm WARN EBADENGINE Unsupported engine { package: 'magicmirror@2.16.0',
npm WARN EBADENGINE   required: { node: '>=12' },
npm WARN EBADENGINE   current: { node: 'v10.24.0', npm: '7.6.3' } }
npm WARN EBADENGINE Unsupported engine { package: 'eslint-plugin-jsdoc@35.4.0',
npm WARN EBADENGINE   required: { node: '>=12' },
npm WARN EBADENGINE   current: { node: 'v10.24.0', npm: '7.6.3' } }
npm WARN EBADENGINE Unsupported engine { package: 'jsdoc-type-pratt-parser@1.0.4',
npm WARN EBADENGINE   required: { node: '>=12.0.0' },
npm WARN EBADENGINE   current: { node: 'v10.24.0', npm: '7.6.3' } }

added 1 package, and audited 922 packages in 6s

**Comment by umglurf** [comment]
Hei, jeg fikk samme problem og så også at jsonpointer manglet. Jeg ser at den er ikke i `package.json` på master branchen, så må legges inn der, da den ikke dras inn av noen av avhengighetene og derfor må legges inn ekspliitt.

**Comment by ottopaulsen** [comment]
Takk for tipset, det hadde jeg ikke tenkt på. Har nå lagt til jsonpointer i package.json pluss oppgradert andre pakker.
Håper det virker nå. Gi tilbakemelding.

**Comment by umglurf** [comment]
Fungerer fint for meg nå, takk
