### ISSUE TITLE
Kommer ikke opp noe i "The gauges" men alt annet ser ut til å virke. Se feilmelding

### ISSUE THREAD

**Issue by kurtern84** [ottopaulsen/MMM-Tibber#18]
Hei! 
Jeg får opp denne feilmeldingen på modulen din:

`0|MagicMir |     at Receiver.emit (events.js:315:20)
0|MagicMir |     at Receiver.dataMessage (/home/pi/MagicMirror/modules/MMM-Tibber/node_modules/ws/lib/receiver.js:517:14)
0|MagicMir |     at Receiver.getData (/home/pi/MagicMirror/modules/MMM-Tibber/node_modules/ws/lib/receiver.js:435:17)
0|MagicMir |     at Receiver.startLoop (/home/pi/MagicMirror/modules/MMM-Tibber/node_modules/ws/lib/receiver.js:143:22)
0|MagicMir |     at Receiver._write (/home/pi/MagicMirror/modules/MMM-Tibber/node_modules/ws/lib/receiver.js:78:10)
0|MagicMir |     at writeOrBuffer (internal/streams/writable.js:358:12)
0|MagicMir |     at Receiver.Writable.write (internal/streams/writable.js:303:10)
0|MagicMir |     at TLSSocket.socketOnData (/home/pi/MagicMirror/modules/MMM-Tibber/node_modules/ws/lib/websocket.js:1077:35)
0|MagicMir |     at TLSSocket.emit (events.js:315:20)
0|MagicMir |     at addChunk (internal/streams/readable.js:309:12)
0|MagicMir |     at readableAddChunk (internal/streams/readable.js:284:9)
0|MagicMir |     at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
0|MagicMir |     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)`

**Comment by ottopaulsen** [comment]
Hei

Kan du legge ut configen for modulen? (Ikke token)
Har dette virket før?
Får du opp data i Tibber-appen?
Får du opp live målinger i Tibber explorer? https://developer.tibber.com/explorer

Otto

**Comment by ottopaulsen** [comment]
Hvis du ikke har Tibber Pulse, så får du ikke data i "guagene". 

Jeg ser du har kopiert hele configen fra dokumentasjonen. Det er ikke lurt.
Det eneste du må ha er tibberToken. Resten har defaultverdier som skal fungere, og så legger du bare inn config for det du vil endre på. Det er defaultverdiene som ligger i dokumentasjonen.

Du bør legge inn `showPowerGauge: false`, `showVoltageGauge: false` og  `showCurrentGauge: false` inntil du får pulse.

Prøv det.
